# Generated by Django 5.2.3 on 2025-07-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="administrative_level",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="रा. प्र. स्तह"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="महाशाखा"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="पद"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="section",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="शाखा"
            ),
        ),
    ]
