# Generated by Django 5.2.3 on 2025-07-02 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planentry",
            name="created_by",
        ),
    ]
