# Generated by Django 5.2.3 on 2025-07-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0003_planentry_created_by"),
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="planentry",
            name="project_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
    ]
