# Generated by Django 5.2.3 on 2025-07-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0007_preassemblyproject"),
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CouncilSubmittedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=15)),
                ("ward_no", models.TextField()),
                (
                    "status",
                    models.CharField(
                        default="नगर सभा सिफारिस भएको परियोजना", max_length=255
                    ),
                ),
                ("priority_no", models.PositiveIntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                    ),
                ),
                (
                    "thematic_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmittedProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=15)),
                ("ward_no", models.TextField()),
                (
                    "status",
                    models.CharField(
                        default="नगर सभा सिफारिस भएको परियोजना", max_length=255
                    ),
                ),
                ("priority_no", models.PositiveIntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                    ),
                ),
                (
                    "thematic_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                    ),
                ),
            ],
        ),
    ]
