# Generated by Django 5.2.3 on 2025-07-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0009_projectsapprovedbymunicipal"),
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MunicipalityLevelProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=255)),
                (
                    "proposed_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("ward_no", models.TextField(blank=True, null=True)),
                (
                    "gps_coordinate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expected_result", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                    ),
                ),
                (
                    "expenditure_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expendituretitle",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.fiscalyear",
                    ),
                ),
                (
                    "project_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.projectlevel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                    ),
                ),
                (
                    "thematic_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.unit",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlanEntry",
        ),
    ]
