# Generated by Django 5.2.3 on 2025-07-03 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0010_municipalitylevelproject_delete_planentry"),
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("ward_level", "Ward-level Project"),
                            ("municipality_level", "Municipality-level Project"),
                            (
                                "ward_requested_thematic",
                                "Projects of Thematic Committees Requested by the Ward",
                            ),
                            ("thematic_committee", "Projects of Thematic Committees"),
                            ("pride_project", "Municipal Pride Project"),
                            ("provincial", "Provincial Government Project"),
                            ("federal", "Federal Government Project"),
                        ],
                        max_length=50,
                    ),
                ),
                ("plan_name", models.CharField(max_length=255)),
                (
                    "proposed_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("ward_no", models.TextField(blank=True, null=True)),
                (
                    "gps_coordinate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expected_result", models.TextField(blank=True, null=True)),
                (
                    "feasibility_study",
                    models.CharField(
                        choices=[("भएको", "भएको"), ("नभएको", "नभएको")], max_length=10
                    ),
                ),
                (
                    "feasibility_file",
                    models.FileField(
                        blank=True, null=True, upload_to="plan/feasibility/"
                    ),
                ),
                (
                    "detailed_study",
                    models.CharField(
                        choices=[("भएको", "भएको"), ("नभएको", "नभएको")], max_length=10
                    ),
                ),
                (
                    "detailed_file",
                    models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
                ),
                (
                    "environmental_study",
                    models.CharField(
                        choices=[("भएको", "भएको"), ("नभएको", "नभएको")], max_length=10
                    ),
                ),
                (
                    "environmental_file",
                    models.FileField(
                        blank=True, null=True, upload_to="plan/environmental/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_plan_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                    ),
                ),
                (
                    "expenditure_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expendituretitle",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.fiscalyear",
                    ),
                ),
                (
                    "project_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.projectlevel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                    ),
                ),
                (
                    "thematic_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.unit",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MunicipalityLevelProject",
        ),
    ]
