# Generated by Django 5.2.3 on 2025-07-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0012_municipalitylevelproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipalitylevelproject",
            name="status",
            field=models.CharField(
                default="प्रविष्टी भएको नगर स्तरीय परियोजना", max_length=255
            ),
        ),
    ]
