# Generated by Django 5.2.3 on 2025-07-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0016_prioritizedthematiccommittee"),
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ThematicCommitteeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        max_length=255, verbose_name="योजना तथा कार्यक्रम"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="बजेट"
                    ),
                ),
                ("ward_no", models.TextField(verbose_name="वडा नंं.")),
                ("status", models.CharField(max_length=255, verbose_name="स्थिती")),
                (
                    "priority_no",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="प्राथमिकता नम्बर"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="अन्य"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                        verbose_name="खर्च केन्द्र",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                        verbose_name="स्रोत",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                        verbose_name="उप-क्षेत्र",
                    ),
                ),
                (
                    "thematic_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                        verbose_name="क्षेत्र",
                    ),
                ),
            ],
        ),
    ]
