# Generated by Django 5.2.3 on 2025-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0018_wardlevelproject_plan_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wardlevelproject",
            name="plan_entry",
        ),
    ]
