# Generated by Django 5.2.3 on 2025-07-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0019_remove_wardlevelproject_plan_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="wardlevelproject",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
