# Generated by Django 5.2.3 on 2025-07-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0022_budgetprogramcommitteewardlevelprogram_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preassemblyproject",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preassemblyproject",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
