# Generated by Django 5.2.3 on 2025-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0025_municipalitylevelproject_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
