# Generated by Django 5.2.3 on 2025-07-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0035_budgetprogramfederalgovernmentprogram"),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardRecommendedProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=255)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=15)),
                ("ward_no", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        default="प्राथमिकरण भएको विषयगत समितिका परियोजना",
                        max_length=255,
                    ),
                ),
                ("priority_no", models.PositiveIntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                    ),
                ),
                (
                    "thematic_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                    ),
                ),
            ],
        ),
    ]
