# Generated by Django 5.2.3 on 2025-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0036_wardrecommendedprojects"),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="municipalityprideproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("priority_no",),
                name="uniq_priority_active_prideproject",
            ),
        ),
    ]
