# Generated by Django 5.2.3 on 2025-07-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0037_municipalityprideproject_uniq_priority_active_prideproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="wardlevelproject",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ward_projects",
                to="planning.planentry",
            ),
        ),
    ]
