# Generated by Django 5.2.3 on 2025-07-25 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0038_wardlevelproject_plan_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="federal_projects",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipality_projects",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pride_projects",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thematic_projects",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="province_projects",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thematic_ward_projects",
                to="planning.planentry",
            ),
        ),
    ]
