# Generated by Django 5.2.3 on 2025-07-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0039_budgetprogramfederalgovernmentprogram_plan_entry_and_more"),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="wardlevelproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="detailed_study",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="environmental_study",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="feasibility_study",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
    ]
