# Generated by Django 5.2.3 on 2025-07-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0040_wardlevelproject_detailed_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planentry",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
