# Generated by Django 5.2.3 on 2025-07-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0041_planentry_location"),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wardlevelproject",
            old_name="remarks",
            new_name="remark",
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
    ]
