# Generated by Django 5.2.3 on 2025-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0042_rename_remarks_wardlevelproject_remark_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wardlevelproject",
            old_name="remark",
            new_name="remarks",
        ),
        migrations.AddField(
            model_name="wardlevelproject",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
