# Generated by Django 5.2.3 on 2025-07-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0043_rename_remark_wardlevelproject_remarks_and_more"),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelproject",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="municipalityprideproject",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="planenteredbythematiccommittee",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="provinciallytransferredprogram",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="wardthematiccommitteeproject",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="ward_no",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="municipalitylevelproject",
            name="ward_no",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="municipalityprideproject",
            name="ward_no",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provinciallytransferredprogram",
            name="status",
            field=models.CharField(
                default="प्रदेश परियोजना अन्तर्गत प्रविष्टी भएको",
                max_length=255,
                verbose_name="स्थिती",
            ),
        ),
        migrations.AlterField(
            model_name="provinciallytransferredprogram",
            name="ward_no",
            field=models.TextField(blank=True, null=True, verbose_name="वडा नंं."),
        ),
        migrations.AlterField(
            model_name="wardthematiccommitteeproject",
            name="ward_no",
            field=models.TextField(blank=True, null=True),
        ),
    ]
