# Generated by Django 5.2.3 on 2025-07-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planning",
            "0044_budgetprogramfederalgovernmentprogram_detailed_file_and_more",
        ),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="wardlevelproject",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddConstraint(
            model_name="municipalitylevelproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("priority_no",),
                name="unique_active_priority_municipality",
            ),
        ),
    ]
