# Generated by Django 5.2.3 on 2025-07-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0045_wardlevelproject_expenditure_title_and_more"),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="wardlevelproject",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
    ]
