# Generated by Django 5.2.3 on 2025-07-30 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0046_wardlevelproject_fiscal_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramfederalgovernmentprogram",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="councilsubmittedproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="municipalitylevelprogram",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="municipalitylevelproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="municipalityprideproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="planenteredbythematiccommittee",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="planentry",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="preassemblyproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="prioritizedthematiccommittee",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="prioritizedwardlevelproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="prioritizedwardlevelthematicproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="projectsapprovedbymunicipal",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="provinciallytransferredprogram",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="submittedprojects",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="thematiccommitteeprogram",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="wardlevelproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="wardrecommendedprojects",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
        migrations.AlterField(
            model_name="wardthematiccommitteeproject",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नं.",
            ),
        ),
    ]
