# Generated by Django 5.2.3 on 2025-07-31 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planning",
            "0047_alter_budgetprogramcommitteewardlevelprogram_ward_no_and_more",
        ),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="detailed_study",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="environmental_study",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="feasibility_study",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="prioritizedwardlevelthematicproject",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AlterField(
            model_name="prioritizedwardlevelthematicproject",
            name="priority_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
