# Generated by Django 5.2.3 on 2025-07-31 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0049_prioritizedwardlevelproject_detailed_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="councilsubmittedproject",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preassemblyproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="preassemblyproject",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="preassemblyproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="preassemblyproject",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="preassemblyproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="preassemblyproject",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prioritizedthematiccommittee",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="prioritizedthematiccommittee",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prioritizedthematiccommittee",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="prioritizedthematiccommittee",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prioritizedthematiccommittee",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="prioritizedthematiccommittee",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="submittedtobudgetmunicipalityprideproject",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_budget_projects",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="wardrecommendedprojects",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="wardrecommendedprojects",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wardrecommendedprojects",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="wardrecommendedprojects",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wardrecommendedprojects",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="wardrecommendedprojects",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
    ]
