# Generated by Django 5.2.3 on 2025-07-31 05:58

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone
import datetime

class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0050_councilsubmittedproject_deleted_at_and_more"),
        ("project_settings", "0003_alter_fiscalyear_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 31, 11, 0, 0)),

            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
                verbose_name="विस्तृत अध्ययन",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
                verbose_name="पर्यावरणीय अध्ययन",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="expected_result",
            field=models.TextField(
                blank=True, null=True, verbose_name="अपेक्षित परिणाम"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
                verbose_name="सम्भाव्यता अध्ययन",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="gps_coordinate",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="GPS समन्वय"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="स्थान"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_program_committee_ward_level_programs",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipality_pride_programs",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogrammunicipalityprideprogram",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="municipalitylevelprogram",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="projectsapprovedbymunicipal",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="expected_result",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="gps_coordinate",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="submittedprojects",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="detailed_file",
            field=models.FileField(blank=True, null=True, upload_to="plan/detailed/"),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="detailed_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
                verbose_name="विस्तृत अध्ययन",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="environmental_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/environmental/"
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="environmental_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
                verbose_name="पर्यावरणीय अध्ययन",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="expected_result",
            field=models.TextField(
                blank=True, null=True, verbose_name="अपेक्षित परिणाम"
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="expenditure_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expendituretitle",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="feasibility_file",
            field=models.FileField(
                blank=True, null=True, upload_to="plan/feasibility/"
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="feasibility_study",
            field=models.CharField(
                blank=True,
                choices=[("भएको", "भएको"), ("नभएको", "नभएको")],
                max_length=10,
                null=True,
                verbose_name="सम्भाव्यता अध्ययन",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="fiscal_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="gps_coordinate",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="GPS समन्वय"
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="स्थान"
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="plan_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thematic_committee_programs",
                to="planning.planentry",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.projectlevel",
            ),
        ),
        migrations.AddField(
            model_name="thematiccommitteeprogram",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="बजेट"
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="expenditure_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.expenditurecenter",
                verbose_name="खर्च केन्द्र",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="plan_name",
            field=models.CharField(max_length=255, verbose_name="योजना तथा कार्यक्रम"),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="priority_no",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="प्राथमिकता नम्बर"
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="अन्य"),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.source",
                verbose_name="स्रोत",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="status",
            field=models.CharField(
                default="बजेट तथा कार्यक्रम तर्जुमा समितिमा सिफारिस भएको वडा स्तरीय परियोजना",
                max_length=255,
                verbose_name="स्थिती",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="sub_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.subarea",
                verbose_name="उप-क्षेत्र",
            ),
        ),
        migrations.AlterField(
            model_name="budgetprogramcommitteewardlevelprogram",
            name="thematic_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.thematicarea",
                verbose_name="क्षेत्र",
            ),
        ),
        migrations.AlterField(
            model_name="thematiccommitteeprogram",
            name="status",
            field=models.CharField(
                default="विषयगत समितिमा सिफारिस गरिएको",
                max_length=255,
                verbose_name="स्थिती",
            ),
        ),
    ]
