# Generated by Django 5.2.3 on 2025-07-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("projects", "0002_alter_mapcostestimate_approver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="user",
        ),
        migrations.AddField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="verificationlog",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_logs",
                to="projects.project",
            ),
        ),
    ]
