# Generated by Django 5.2.3 on 2025-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_verificationlog_approver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationlog",
            name="uploader_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="verificationlog",
            name="uploader_role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
