# Generated by Django 5.2.3 on 2025-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalyear",
            name="year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
