# Generated by Django 5.2.3 on 2025-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupplierRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                (
                    "correspondence_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=20)),
                (
                    "telephone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("company_registration_number", models.CharField(max_length=50)),
                ("pan_number", models.CharField(max_length=50)),
                ("has_registration_certificate", models.BooleanField()),
                ("is_renewed", models.BooleanField()),
                ("has_vat_pan_certificate", models.BooleanField()),
                ("has_tax_clearance", models.BooleanField()),
                ("has_license_copy", models.BooleanField()),
                ("goods_description", models.TextField(blank=True, null=True)),
                ("construction_description", models.TextField(blank=True, null=True)),
                ("consulting_description", models.TextField(blank=True, null=True)),
                ("other_services_description", models.TextField(blank=True, null=True)),
                (
                    "registration_certificate_file",
                    models.FileField(blank=True, null=True, upload_to="supplier_docs/"),
                ),
                (
                    "license_file",
                    models.FileField(blank=True, null=True, upload_to="supplier_docs/"),
                ),
                (
                    "tax_clearance_file",
                    models.FileField(blank=True, null=True, upload_to="supplier_docs/"),
                ),
                (
                    "pan_file",
                    models.FileField(blank=True, null=True, upload_to="supplier_docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
