# Generated by Django 5.2.3 on 2025-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierregistry",
            name="existing_inventory_list",
            field=models.FileField(
                blank=True,
                help_text="Upload the current inventory list document",
                null=True,
                upload_to="supplier_docs/",
            ),
        ),
    ]
