# Generated by Django 5.2.3 on 2025-07-04 07:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import projects.models.Operation_Location.operation_location
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerCommitteeUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField(unique=True)),
                ("file", models.FileField(upload_to="consumer_committee_uploads/")),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CostEstimateDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "contingency_percent",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
                ),
                (
                    "allocated_budget",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "contingency_amount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=12
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CostEstimateRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prev_estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "prev_contingency_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "prev_contingency_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "prev_total_estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "revised_estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "revised_contingency_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "revised_contingency_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "revised_total_estimated_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cost_estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects.costestimatedetail",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(blank=True, max_length=255)),
                (
                    "ward_no",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "वडा नं 1"),
                            (2, "वडा नं 2"),
                            (3, "वडा नं 3"),
                            (4, "वडा नं 4"),
                            (5, "वडा नं 5"),
                            (6, "वडा नं 6"),
                            (7, "वडा नं 7"),
                            (8, "वडा नं 8"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, null=True, verbose_name="सम्पन्\u200dन गर्ने परिणाम"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="बजेट",
                    ),
                ),
                (
                    "location_gps",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="योजना संचालन स्थानको GPS CO-ORDINATE",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("process_ensured", "सुचारु प्रक्रिया सुनिस्चित भएको"),
                            ("completed", "सम्पन्न भएको"),
                            ("not_started", "सुरु नभएको"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="स्थिती",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.thematicarea",
                    ),
                ),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.expenditurecenter",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.fiscalyear",
                    ),
                ),
                (
                    "project_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.projectlevel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.source",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.subarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeneficiaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("total_households", "जम्मा परिवार"),
                            ("total_population", "जम्मा जनसंख्या"),
                            ("indigenous_families", "आदिवासी जनजातिको परिवार संख्या"),
                            ("dalit_families", "दलित वर्गको परिवार संख्या"),
                            ("children_population", "बालबालिकाको जनसंख्या"),
                            ("other_families", "अन्य वर्गको परिवार संख्या"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "female",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("male", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "other",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("total", models.PositiveIntegerField()),
                (
                    "program_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to="projects.programdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("serial_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "project_name",
                    models.CharField(
                        max_length=255, verbose_name="योजना तथा कार्यक्रम"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="बजेट"
                    ),
                ),
                (
                    "ward_no",
                    models.IntegerField(
                        choices=[
                            (1, "वडा नंं. 1"),
                            (2, "वडा नंं. 2"),
                            (3, "वडा नंं. 3"),
                            (4, "वडा नंं. 4"),
                            (5, "वडा नंं. 5"),
                            (6, "वडा नंं. 6"),
                            (7, "वडा नंं. 7"),
                            (8, "वडा नंं. 8"),
                        ],
                        verbose_name="वडा नंं.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("process_ensured", "सुचारु प्रक्रिया सुनिस्चित भएको"),
                            ("completed", "सम्पन्न भएको"),
                            ("not_started", "सुरु नभएको"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="स्थिती",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=255, null=True, verbose_name="योजना संचालन स्थान"
                    ),
                ),
                (
                    "location_gps",
                    models.CharField(
                        max_length=100, null=True, verbose_name="GPS CO-ORDINATE"
                    ),
                ),
                (
                    "outcome",
                    models.TextField(null=True, verbose_name="सम्पन गर्ने परिणाम"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                        verbose_name="क्षेत्र",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                        verbose_name="खर्च केन्द्र",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.fiscalyear",
                        verbose_name="आर्थिक वर्ष",
                    ),
                ),
                (
                    "project_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.projectlevel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                        verbose_name="स्रोत",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                        verbose_name="उप-क्षेत्र",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.unit",
                        verbose_name="ईकाइ",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="programdetail",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="PaymentRelatedDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("पहिलो पेश्की भुक्तानी", "पहिलो पेश्की भुक्तानी"),
                            ("दोस्रो किस्ता भुक्तानी", "दोस्रो किस्ता भुक्तानी"),
                            ("अन्तिम किस्ता भुक्तानी", "अन्तिम किस्ता भुक्तानी"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "physical_progress",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationSitePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.IntegerField(
                        choices=[
                            (1, "निर्माण कार्य गर्नु पुर्वको फोटोहरु"),
                            (2, "योजनाको निर्माण कार्य भैरहेको अवस्थाको फोटोहरु"),
                            (3, "योजनाको निर्माण कार्य सकिएपछीका फोटोहरु"),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.Operation_Location.operation_location.upload_to_operation_site,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_site_photos",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficialDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("अध्यक्ष", "अध्यक्ष"),
                            ("सचिव", "सचिव"),
                            ("कोषाध्यक्ष", "कोषाध्यक्ष"),
                            ("सदस्य", "सदस्य"),
                        ],
                        max_length=50,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("पुरुष", "पुरुष"),
                            ("महिला", "महिला"),
                            ("अन्य", "अन्य"),
                        ],
                        max_length=10,
                    ),
                ),
                ("citizenship_no", models.CharField(max_length=100)),
                (
                    "citizenship_front",
                    models.FileField(upload_to="officials/citizenship/front/"),
                ),
                (
                    "citizenship_back",
                    models.FileField(upload_to="officials/citizenship/back/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officials",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringFacilitationCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("संयोजक", "संयोजक"),
                            ("सदस्य सचिव", "सदस्य सचिव"),
                            ("सदस्य", "सदस्य"),
                        ],
                        max_length=50,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("पुरुष", "पुरुष"),
                            ("महिला", "महिला"),
                            ("अन्य", "अन्य"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("citizenship_no", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=20)),
                (
                    "citizenship_front",
                    models.FileField(
                        upload_to="monitoring_committee/citizenship/front/"
                    ),
                ),
                (
                    "citizenship_back",
                    models.FileField(
                        upload_to="monitoring_committee/citizenship/back/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_committee",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MapCostEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            (
                                "सम्भव्यता अध्यायन प्रतिवेदन",
                                "सम्भव्यता अध्यायन प्रतिवेदन",
                            ),
                            ("नक्सा", "नक्सा"),
                            (
                                "लागत अनुमान (लागत इष्टिमेट)",
                                "लागत अनुमान (लागत इष्टिमेट)",
                            ),
                            ("प्राविधिक प्रतिवेदन", "प्राविधिक प्रतिवेदन"),
                            ("निर्माण कार्य तालिका", "निर्माण कार्य तालिका"),
                            (
                                "लागत अनुमान स्विकृती सम्बन्धी टिप्पणी आदेश",
                                "लागत अनुमान स्विकृती सम्बन्धी टिप्पणी आदेश",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="map_cost_estimates/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, default="", max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_cost_estimates",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InitiationProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initiation_method",
                    models.CharField(
                        choices=[
                            ("उपभोक्ता समिति मार्फत", "उपभोक्ता समिति मार्फत"),
                            ("सिलबन्दि दरभाउपत्र मार्फत", "सिलबन्दि दरभाउपत्र मार्फत"),
                            ("बोलपत्र मार्फत", "बोलपत्र मार्फत"),
                            ("अमानत मार्फत", "अमानत मार्फत"),
                            ("सोझै खरिद", "सोझै खरिद"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("has_consumer_committee", models.BooleanField(default=False)),
                ("has_agreement", models.BooleanField(default=False)),
                ("has_payment_installment", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiation_processes",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FirstInstallmentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField(unique=True)),
                ("file", models.FileField(upload_to="first_installment_uploads/")),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_installments",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/documents/")),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="costestimatedetail",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_estimate",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="ConsumerCommitteeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer_committee_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("formation_date", models.DateField()),
                ("representative_name", models.CharField(max_length=255)),
                ("representative_position", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_committees",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(max_length=255, verbose_name="बैंकको साखा"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_settings.bank",
                        verbose_name="बैंकको नाम",
                    ),
                ),
                (
                    "signatories",
                    models.ManyToManyField(
                        related_name="bank_signatories",
                        to="projects.officialdetail",
                        verbose_name="दस्तखत कर्ता",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="projects.project",
                        verbose_name="आयोजनाको नाम",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankAccountRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("बैंक खाता सञ्चालन सिफारिस", "बैंक खाता सञ्चालन सिफारिस")
                        ],
                        default="बैंक खाता सञ्चालन सिफारिस",
                        max_length=255,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("status", models.CharField(blank=True, max_length=100)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="bank_recommendation/"
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_recommendations",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_account_number", models.CharField(max_length=50)),
                (
                    "check_photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="account_check_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recommendation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_account_photo",
                        to="projects.bankaccountrecommendation",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_photo",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectAgreementDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="लागत अनुमान",
                    ),
                ),
                (
                    "contingency_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="कन्टिन्जेन्सि रकम",
                    ),
                ),
                (
                    "contingency_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="कन्टिन्जेन्सि प्रतिशत",
                    ),
                ),
                (
                    "total_cost_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="कुल लागत अनुमान",
                    ),
                ),
                (
                    "agreement_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="सम्झौता रकम रु."
                    ),
                ),
                ("agreement_date", models.DateField(verbose_name="सम्झौता मिति")),
                (
                    "municipality_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="नगरपालिकाले ब्यहेर्ने रकम",
                    ),
                ),
                (
                    "municipality_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="नगरपालिकाले ब्यहेर्ने रकमको प्रतिशत (%)",
                    ),
                ),
                (
                    "public_participation_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="जनसहभागिता",
                    ),
                ),
                (
                    "public_participation_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="जनसहभागिताले ब्यहेर्ने रकमको प्रतिशत (%)",
                    ),
                ),
                ("work_order_date", models.DateField(verbose_name="कार्यादेश मिति")),
                (
                    "completion_date",
                    models.DateField(verbose_name="कार्य सम्पन्न गर्नुपर्ने मिति"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_details",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_completion_date",
                    models.DateField(verbose_name="अघिल्लो सम्पन्न मिति"),
                ),
                (
                    "extended_completion_date",
                    models.DateField(verbose_name="नयाँ सम्पन्न मिति"),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="म्याद थप गर्ने कारण"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="projects.projectagreementdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectAgreementWorkorderUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField(unique=True)),
                (
                    "file",
                    models.FileField(upload_to="project_agreement_workorder_uploads/"),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_aggrement_workorder",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "serial_no")},
            },
        ),
        migrations.CreateModel(
            name="ProjectPlanTrackerUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="project_plan_tracker_uploads/")),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_tracker_uploads",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "serial_no")},
            },
        ),
        migrations.CreateModel(
            name="ProjectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_key", models.CharField(max_length=100)),
                ("stage_label", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "stage_key")},
            },
        ),
        migrations.CreateModel(
            name="SecondInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="second_installment_uploads/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_installments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "serial_no")},
            },
        ),
        migrations.CreateModel(
            name="ThirdInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="third_installment_uploads/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_installments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "serial_no")},
            },
        ),
    ]
