# Generated by Django 5.2.3 on 2025-06-26 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("serial_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "project_name",
                    models.CharField(
                        max_length=255, verbose_name="योजना तथा कार्यक्रम"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="बजेट"
                    ),
                ),
                ("ward_no", models.PositiveIntegerField(verbose_name="वडा नंं.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("process_ensured", "सुचारु प्रक्रिया सुनिस्चित भएको"),
                            ("completed", "सम्पन्न भएको"),
                            ("not_started", "सुरु नभएको"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="स्थिती",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.thematicarea",
                        verbose_name="क्षेत्र",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.expenditurecenter",
                        verbose_name="खर्च केन्द्र",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.fiscalyear",
                        verbose_name="आर्थिक वर्ष",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.source",
                        verbose_name="स्रोत",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project_settings.subarea",
                        verbose_name="उप-क्षेत्र",
                    ),
                ),
            ],
        ),
    ]
