# Generated by Django 5.2.3 on 2025-06-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="ward_no",
            field=models.IntegerField(
                choices=[
                    (1, "वडा नंं. 1"),
                    (2, "वडा नंं. 2"),
                    (3, "वडा नंं. 3"),
                    (4, "वडा नंं. 4"),
                    (5, "वडा नंं. 5"),
                    (6, "वडा नंं. 6"),
                    (7, "वडा नंं. 7"),
                    (8, "वडा नंं. 8"),
                ],
                verbose_name="वडा नंं.",
            ),
        ),
        migrations.CreateModel(
            name="InitiationProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initiation_method",
                    models.CharField(
                        choices=[
                            ("उपभोक्ता समिति मार्फत", "उपभोक्ता समिति मार्फत"),
                            ("सिलबन्दि दरभाउपत्र मार्फत", "सिलबन्दि दरभाउपत्र मार्फत"),
                            ("बोलपत्र मार्फत", "बोलपत्र मार्फत"),
                            ("अमानत मार्फत", "अमानत मार्फत"),
                            ("सोझै खरिद", "सोझै खरिद"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("has_consumer_committee", models.BooleanField(default=False)),
                ("has_agreement", models.BooleanField(default=False)),
                ("has_payment_installment", models.BooleanField(default=False)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
