# Generated by Django 5.2.3 on 2025-06-28 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankdetail",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_details",
                to="projects.project",
                verbose_name="आयोजनाको नाम",
            ),
        ),
    ]
