# Generated by Django 5.2.3 on 2025-07-04 09:17
from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_person_user_person_name_and_more"),
        ("projects", "0002_alter_mapcostestimate_approver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiationprocess",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="mapcostestimate",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_docs",
                to=settings.AUTH_USER_MODEL,

            ),
        ),
        migrations.AlterField(
            model_name="mapcostestimate",
            name="checker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_docs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
