# Generated by Django 5.2.3 on 2025-06-28 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_bankdetail_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRelatedDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("पहिलो पेश्की भुक्तानी", "पहिलो पेश्की भुक्तानी"),
                            ("दोस्रो किस्ता भुक्तानी", "दोस्रो किस्ता भुक्तानी"),
                            ("अन्तिम किस्ता भुक्तानी", "अन्तिम किस्ता भुक्तानी"),
                        ],
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "physical_progress",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
