# Generated by Django 5.2.3 on 2025-06-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
        ("projects", "0003_consumercommitteeupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(
                max_length=255, null=True, verbose_name="योजना संचालन स्थान"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="location_gps",
            field=models.CharField(
                max_length=100, null=True, verbose_name="GPS CO-ORDINATE"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="outcome",
            field=models.TextField(null=True, verbose_name="सम्पन गर्ने परिणाम"),
        ),
        migrations.AddField(
            model_name="project",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="project_settings.unit",
                verbose_name="ईकाइ",
            ),
        ),
    ]
