# Generated by Django 5.2.3 on 2025-06-28 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_paymentrelateddetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrelateddetail",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
