# Generated by Django 5.2.3 on 2025-06-28 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_paymentrelateddetail_issue_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccountRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("बैंक खाता सञ्चालन सिफारिस", "बैंक खाता सञ्चालन सिफारिस")
                        ],
                        default="बैंक खाता सञ्चालन सिफारिस",
                        max_length=255,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("status", models.CharField(blank=True, max_length=100)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="bank_recommendation/"
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_recommendations",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
