# Generated by Django 5.2.3 on 2025-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_mapcostestimate_approver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("process_ensured", "सुचारु प्रक्रिया सुनिस्चित भएको"),
                    ("completed", "सम्पन्न भएको"),
                    ("not_started", "सुरु नभएको"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="स्थिती",
            ),
        ),
    ]
