# Generated by Django 5.2.3 on 2025-06-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
        ("projects", "0004_project_location_project_location_gps_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(blank=True, max_length=255)),
                (
                    "ward_no",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "वडा नं 1"),
                            (2, "वडा नं 2"),
                            (3, "वडा नं 3"),
                            (4, "वडा नं 4"),
                            (5, "वडा नं 5"),
                            (6, "वडा नं 6"),
                            (7, "वडा नं 7"),
                            (8, "वडा नं 8"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, null=True, verbose_name="सम्पन्\u200dन गर्ने परिणाम"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="बजेट",
                    ),
                ),
                (
                    "location_gps",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="योजना संचालन स्थानको GPS CO-ORDINATE",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("process_ensured", "सुचारु प्रक्रिया सुनिस्चित भएको"),
                            ("completed", "सम्पन्न भएको"),
                            ("not_started", "सुरु नभएको"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="स्थिती",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.thematicarea",
                    ),
                ),
                (
                    "expenditure_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.expenditurecenter",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.fiscalyear",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "project_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.projectlevel",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.source",
                    ),
                ),
                (
                    "sub_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_settings.subarea",
                    ),
                ),
            ],
        ),
    ]
