# Generated by Django 5.2.3 on 2025-06-28 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_bankaccountrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_account_number", models.CharField(max_length=50)),
                (
                    "check_photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="account_check_photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_photo",
                        to="projects.project",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_account_photo",
                        to="projects.bankaccountrecommendation",
                    ),
                ),
            ],
        ),
    ]
