# Generated by Django 5.2.3 on 2025-07-07 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiarydetail",
            name="program_detail",
        ),
        migrations.AddField(
            model_name="beneficiarydetail",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_details",
                to="projects.project",
            ),
        ),
    ]
