# Generated by Django 5.2.3 on 2025-06-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_settings",
            "0002_bank_expenditurecenter_expendituretitle_fiscalyear_and_more",
        ),
        ("projects", "0005_programdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_settings.projectlevel",
            ),
        ),
    ]
