# Generated by Django 5.2.3 on 2025-06-28 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("projects", "0006_accountphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapCostEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            (
                                "सम्भव्यता अध्यायन प्रतिवेदन",
                                "सम्भव्यता अध्यायन प्रतिवेदन",
                            ),
                            ("नक्सा", "नक्सा"),
                            (
                                "लागत अनुमान (लागत इष्टिमेट)",
                                "लागत अनुमान (लागत इष्टिमेट)",
                            ),
                            ("प्राविधिक प्रतिवेदन", "प्राविधिक प्रतिवेदन"),
                            ("निर्माण कार्य तालिका", "निर्माण कार्य तालिका"),
                            (
                                "लागत अनुमान स्विकृती सम्बन्धी टिप्पणी आदेश",
                                "लागत अनुमान स्विकृती सम्बन्धी टिप्पणी आदेश",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="map_cost_estimates/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, default="", max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_docs",
                        to="authentication.person",
                    ),
                ),
                (
                    "checker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_docs",
                        to="authentication.person",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_cost_estimates",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
