# Generated by Django 5.2.3 on 2025-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_remove_beneficiarydetail_program_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrelateddetail",
            name="uploaded_file",
            field=models.FileField(
                blank=True, null=True, upload_to="payment_related_files/"
            ),
        ),
    ]
