# Generated by Django 5.2.3 on 2025-06-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_project_project_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("total_households", "जम्मा परिवार"),
                            ("total_population", "जम्मा जनसंख्या"),
                            ("indigenous_families", "आदिवासी जनजातिको परिवार संख्या"),
                            ("dalit_families", "दलित वर्गको परिवार संख्या"),
                            ("children_population", "बालबालिकाको जनसंख्या"),
                            ("other_families", "अन्य वर्गको परिवार संख्या"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "female",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("male", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "other",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("total", models.PositiveIntegerField()),
                (
                    "program_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to="projects.programdetail",
                    ),
                ),
            ],
        ),
    ]
