# Generated by Django 5.2.3 on 2025-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_beneficiarydetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerCommitteeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer_committee_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("formation_date", models.DateField()),
                ("representative_name", models.CharField(max_length=255)),
                ("representative_position", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
