# Generated by Django 5.2.3 on 2025-07-12 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_paymentrelateddetail_uploaded_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrelateddetail",
            name="amount_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paymentrelateddetail",
            name="issue_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.localdate, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paymentrelateddetail",
            name="physical_progress",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
