# Generated by Django 5.2.3 on 2025-07-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_settings", "0003_alter_fiscalyear_year"),
        ("projects", "0008_alter_paymentrelateddetail_amount_paid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostEstimationCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provincial_budget",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("local_budget", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_without_vat",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("ps_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "vat_percent",
                    models.DecimalField(decimal_places=2, default=13.0, max_digits=5),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "contingency_percent",
                    models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
                ),
                (
                    "contingency_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_estimates",
                        to="project_settings.fiscalyear",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_estimates",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
