# Generated by Django 5.2.3 on 2025-06-29 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_extendeddeadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostEstimateRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prev_estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "prev_contingency_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "prev_contingency_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "prev_total_estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "revised_estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "revised_contingency_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "revised_contingency_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "revised_total_estimated_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cost_estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="projects.costestimatedetail",
                    ),
                ),
                (
                    "revised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
