# Generated by Django 5.2.3 on 2025-06-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_consumercommitteedetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("अध्यक्ष", "अध्यक्ष"),
                            ("सचिव", "सचिव"),
                            ("कोषाध्यक्ष", "कोषाध्यक्ष"),
                            ("सदस्य", "सदस्य"),
                        ],
                        max_length=50,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("contact_no", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("पुरुष", "पुरुष"),
                            ("महिला", "महिला"),
                            ("अन्य", "अन्य"),
                        ],
                        max_length=10,
                    ),
                ),
                ("citizenship_no", models.CharField(max_length=100)),
                (
                    "citizenship_front",
                    models.FileField(upload_to="officials/citizenship/front/"),
                ),
                (
                    "citizenship_back",
                    models.FileField(upload_to="officials/citizenship/back/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officials",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
