# Generated by Django 5.2.3 on 2025-06-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_costestimaterevision"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_key", models.CharField(max_length=100)),
                ("stage_label", models.CharField(max_length=255)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "stage_key")},
            },
        ),
    ]
