# Generated by Django 5.2.3 on 2025-06-27 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_officialdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringFacilitationCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("संयोजक", "संयोजक"),
                            ("सदस्य सचिव", "सदस्य सचिव"),
                            ("सदस्य", "सदस्य"),
                        ],
                        max_length=50,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("पुरुष", "पुरुष"),
                            ("महिला", "महिला"),
                            ("अन्य", "अन्य"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("citizenship_no", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=20)),
                (
                    "citizenship_front",
                    models.FileField(
                        upload_to="monitoring_committee/citizenship/front/"
                    ),
                ),
                (
                    "citizenship_back",
                    models.FileField(
                        upload_to="monitoring_committee/citizenship/back/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_committee",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
