# Generated by Django 5.2.3 on 2025-06-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_monitoringfacilitationcommitteemember"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostEstimateDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_budget",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "contingency_percent",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
                ),
                (
                    "contingency_amount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=12
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_estimate",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
