# Generated by Django 5.2.3 on 2025-07-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_worktype_workprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialdetail",
            name="citizenship_back",
            field=models.FileField(
                blank=True, null=True, upload_to="officials/citizenship/back/"
            ),
        ),
        migrations.AlterField(
            model_name="officialdetail",
            name="citizenship_front",
            field=models.FileField(
                blank=True, null=True, upload_to="officials/citizenship/front/"
            ),
        ),
    ]
