# Generated by Django 5.2.3 on 2025-06-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_projectprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumercommitteedetail",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer_committees",
                to="projects.project",
            ),
        ),
    ]
