# Generated by Django 5.2.3 on 2025-06-27 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_costestimatedetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costestimatedetail",
            name="allocated_budget",
        ),
    ]
