# Generated by Django 5.2.3 on 2025-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_alter_officialdetail_citizenship_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialdetail",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="officialdetail",
            name="citizenship_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="officialdetail",
            name="contact_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="officialdetail",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="officialdetail",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("पुरुष", "पुरुष"), ("महिला", "महिला"), ("अन्य", "अन्य")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="officialdetail",
            name="post",
            field=models.CharField(
                blank=True,
                choices=[
                    ("अध्यक्ष", "अध्यक्ष"),
                    ("सचिव", "सचिव"),
                    ("कोषाध्यक्ष", "कोषाध्यक्ष"),
                    ("सदस्य", "सदस्य"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="officialdetail",
            name="serial_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
