# Generated by Django 5.2.3 on 2025-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_projectplantrackerupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAgreementWorkorderUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField(unique=True)),
                (
                    "file",
                    models.FileField(upload_to="project_agreement_workorder_uploads/"),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
