# Generated by Django 5.2.3 on 2025-07-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_alter_officialdetail_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringfacilitationcommitteemember",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringfacilitationcommitteemember",
            name="citizenship_back",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="monitoring_committee/citizenship/back/",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringfacilitationcommitteemember",
            name="citizenship_front",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="monitoring_committee/citizenship/front/",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringfacilitationcommitteemember",
            name="citizenship_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringfacilitationcommitteemember",
            name="contact_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringfacilitationcommitteemember",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringfacilitationcommitteemember",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("पुरुष", "पुरुष"), ("महिला", "महिला"), ("अन्य", "अन्य")],
                max_length=10,
                null=True,
            ),
        ),
    ]
