# Generated by Django 5.2.3 on 2025-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_remove_costestimatedetail_allocated_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="costestimatedetail",
            name="allocated_budget",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
