# Generated by Django 5.2.3 on 2025-06-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_projectagreementworkorderupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectagreementworkorderupload",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_aggrement_workorder",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectplantrackerupload",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_tracker_uploads",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectplantrackerupload",
            name="serial_no",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="projectplantrackerupload",
            unique_together={("project", "serial_no")},
        ),
    ]
