# Generated by Django 5.2.3 on 2025-06-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_costestimatedetail_allocated_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAgreementDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="लागत अनुमान",
                    ),
                ),
                (
                    "contingency_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="कन्टिन्जेन्सि रकम",
                    ),
                ),
                (
                    "contingency_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="कन्टिन्जेन्सि प्रतिशत",
                    ),
                ),
                (
                    "total_cost_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="कुल लागत अनुमान",
                    ),
                ),
                (
                    "agreement_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="सम्झौता रकम रु."
                    ),
                ),
                ("agreement_date", models.DateField(verbose_name="सम्झौता मिति")),
                (
                    "municipality_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="नगरपालिकाले ब्यहेर्ने रकम",
                    ),
                ),
                (
                    "municipality_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="नगरपालिकाले ब्यहेर्ने रकमको प्रतिशत (%)",
                    ),
                ),
                (
                    "public_participation_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="जनसहभागिता",
                    ),
                ),
                (
                    "public_participation_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="जनसहभागिताले ब्यहेर्ने रकमको प्रतिशत (%)",
                    ),
                ),
                ("work_order_date", models.DateField(verbose_name="कार्यादेश मिति")),
                (
                    "completion_date",
                    models.DateField(verbose_name="कार्य सम्पन्न गर्नुपर्ने मिति"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_details",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
