# Generated by Django 5.2.3 on 2025-07-20 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0013_alter_monitoringfacilitationcommitteemember_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programdetail",
            name="area",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="expenditure_center",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="fiscal_year",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="location_gps",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="outcome",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="project_level",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="project_name",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="source",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="status",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="sub_area",
        ),
        migrations.RemoveField(
            model_name="programdetail",
            name="ward_no",
        ),
    ]
