# Generated by Django 5.2.3 on 2025-06-27 18:16

import django.db.models.deletion
import projects.models.operation_location
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_projectagreementdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationSitePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_no",
                    models.IntegerField(
                        choices=[
                            (1, "निर्माण कार्य गर्नु पुर्वको फोटोहरु"),
                            (2, "योजनाको निर्माण कार्य भैरहेको अवस्थाको फोटोहरु"),
                            (3, "योजनाको निर्माण कार्य सकिएपछीका फोटोहरु"),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        upload_to=projects.models.operation_location.upload_to_operation_site
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_site_photos",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
