# Generated by Django 5.2.3 on 2025-07-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_remove_programdetail_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumercommitteeupload",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer_uploads",
                to="projects.project",
            ),
        ),
    ]
