# Generated by Django 5.2.3 on 2025-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_consumercommitteeupload_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("process_ensured", "सुचारु प्रक्रिया सुनिस्चित भएको"),
                    ("completed", "सम्पन्न भएको"),
                    ("not_started", "सुरु नभएको"),
                ],
                default="not_started",
                max_length=20,
                null=True,
                verbose_name="स्थिती",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
