# Generated by Django 5.2.3 on 2025-06-27 18:19

import projects.models.operation_location
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_operationsitephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationsitephoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=projects.models.operation_location.upload_to_operation_site,
            ),
        ),
    ]
