# Generated by Django 5.2.3 on 2025-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_alter_project_created_at_alter_project_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumercommitteeupload",
            name="serial_no",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="consumercommitteeupload",
            unique_together={("project", "serial_no")},
        ),
    ]
