# Generated by Django 5.2.3 on 2025-06-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_document_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "serial_no")},
            },
        ),
    ]
