# Generated by Django 5.2.3 on 2025-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_alter_consumercommitteeupload_serial_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectagreementworkorderupload",
            name="serial_no",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="projectagreementworkorderupload",
            unique_together={("project", "serial_no")},
        ),
    ]
