# Generated by Django 5.2.3 on 2025-07-30 14:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_alter_projectagreementworkorderupload_serial_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="ward_no",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "वडा नंं. 1"),
                        (2, "वडा नंं. 2"),
                        (3, "वडा नंं. 3"),
                        (4, "वडा नंं. 4"),
                        (5, "वडा नंं. 5"),
                        (6, "वडा नंं. 6"),
                        (7, "वडा नंं. 7"),
                        (8, "वडा नंं. 8"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="वडा नंं.",
            ),
        ),
    ]
