# Generated by Django 5.2.3 on 2025-07-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_firstinstallmentupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstinstallmentupload",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_installments",
                to="projects.project",
            ),
        ),
    ]
