# Generated by Django 5.2.3 on 2025-07-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_firstinstallmentupload_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="second_installment_uploads/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_installments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "serial_no")},
            },
        ),
    ]
