# Generated by Django 5.2.3 on 2025-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_alter_project_ward_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstinstallmentupload",
            name="serial_no",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="firstinstallmentupload",
            unique_together={("project", "serial_no")},
        ),
    ]
